package problems;

import java.util.stream.Stream;

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
public class Problem002 {
    public static void main(String[] args) {
        Long result = Stream.iterate(new Long[]{1L, 1L}, f -> new Long[]{f[1], f[0] + f[1]})
                .limit(40)
                .filter(f -> f[1] % 2 == 0 && f[1] < 4000000)
                .mapToLong(f -> f[1]).sum();
        System.out.println(result);
    }
}
